export const SET_PRODUCTS = 'SET_PRODUCTS'
export const TOGGLE_ITEM_IN_WISHLIST = 'TOGGLE_ITEM_IN_WISHLIST'
export const TOGGLE_ITEM_IN_CART = 'TOGGLE_ITEM_IN_CART'
export const ON_CART_VISIBILITY_TOGGLE = 'ON_CART_VISIBILITY_TOGGLE'
